#pragma once

enum {
	TOKEN_GROUP_DEFINED_WORD = 0,
	TOKEN_GROUP_DEFINED_SYMBOL,
	TOKEN_GROUP_STRING_CONST,
	TOKEN_GROUP_NUMB_CONST,
	TOKEN_GROUP_COMMENT,
	TOKEN_GROUP_VARIABLE,
	TOKEN_GROUP_UNRECOGNISED
};